### ISSUE TITLE
Oi

### ISSUE THREAD

**Issue by gibatronic** [gibatronic/gibatronic.github.com#11]
@jpoppe

**Comment by rafael-pinheiro** [comment]
Poppe!!!!!!!

**Comment by jpoppe** [comment]
Yo @gibatronic and @rafael-pinheiro , that's creative :)

Let's meet!

Maybe next Monday the 16th?

**Comment by gibatronic** [comment]
aw yiss!
and it's going to be St. Patrick's eve

**Comment by jpoppe** [comment]
Cool let's do it!

**Comment by gibatronic** [comment]
https://wa.me/31618252727
